networks:
  web: {}

volumes:
  mysql_data: {}
  caddy_data: {}
  caddy_config: {}

services:
  # INGRESS ÚNICO con HTTPS automático
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    networks: [web]
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Para que Caddy se registre en ACME con tu correo
      ACME_AGREE: "true"
      # No es obligatorio, pero puedes fijar email con: 
      # EMAIL: sebas517@hotmail.com
    volumes:
      - ./despliegue-asrm/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      # estáticos del sitio raíz y presentacion
      - ./web-personal:/srv/web-personal:ro
      - ./presentacion:/srv/presentacion:ro

  # PHP-FPM (Laravel)
  clinicamv-php:
    image: ghcr.io/sebasrodmag/clinicamv-php:main
    container_name: clinicamv-php
    restart: unless-stopped
    networks: [web]
    depends_on:
      mysql:
        condition: service_healthy
    # usa tu entrypoint si lo tienes (opcional)
    # entrypoint: ["/usr/local/bin/laravel-entrypoint.sh"]
    volumes:
      - ./despliegue-asrm/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      # si usas entrypoint + plantilla:
      # - ./despliegue-asrm/php/laravel-entrypoint.sh:/usr/local/bin/laravel-entrypoint.sh:ro
      # - ./despliegue-asrm/laravel/.env.template:/var/www/.env.template:ro
    environment:
      APP_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: clinica_db
      DB_USERNAME: clinica
      DB_PASSWORD: clinica
      CACHE_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      TRUSTED_PROXIES: "*"
      TZ: Europe/Madrid

  # FRONTEND (opcional): si quieres seguir usando la imagen actual
  clinicamv-frontend:
    image: ghcr.io/sebasrodmag/clinicamv-frontend:main
    container_name: clinicamv-frontend
    restart: unless-stopped
    networks: [web]

  # DB
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks: [web]
    environment:
      MYSQL_DATABASE: clinica_db
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: clinica
      TZ: Europe/Madrid
    command: ["--default-authentication-plugin=mysql_native_password","--sql-mode="]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
