networks:
  web: {}

volumes:
  traefik_letsencrypt: {}

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    networks: [web]
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web-personal:
    image: nginx:alpine
    container_name: web-personal
    restart: unless-stopped
    networks: [web]
    volumes:
      - ./web-personal:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)
      - traefik.http.routers.personal.entrypoints=websecure
      - traefik.http.routers.personal.tls.certresolver=le
      - traefik.http.routers.personal.priority=1

  presentacion:
    image: nginx:alpine
    container_name: presentacion
    restart: unless-stopped
    networks: [web]
    volumes:
      - ./presentacion:/usr/share/nginx/html/presentacion:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.presentacion.rule=Host(`${DOMAIN}`) && PathPrefix(`/presentacion`)
      - traefik.http.routers.presentacion.entrypoints=websecure
      - traefik.http.routers.presentacion.tls.certresolver=le
      - traefik.http.routers.presentacion.priority=10

#FRONTEND Angular servido en /clinicamv
  clinicamv-frontend:
    image: ghcr.io/SebasRodMag/clinicamv-frontend:main
    container_name: clinicamv-frontend
    restart: unless-stopped
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.clinicamv.rule=Host(`${DOMAIN}`) && PathPrefix(`/clinicamv`)
      - traefik.http.routers.clinicamv.entrypoints=websecure
      - traefik.http.routers.clinicamv.tls.certresolver=le
      - traefik.http.routers.clinicamv.priority=20

  clinicamv-php:
    image: ghcr.io/SebasRodMag/clinicamv-php:main
    container_name: clinicamv-php
    restart: unless-stopped
    networks: [web]
    environment:
      APP_ENV: production

  clinicamv-api:
    image: ghcr.io/SebasRodMag/clinicamv-api:main
    container_name: clinicamv-api
    restart: unless-stopped
    depends_on: [clinicamv-php]
    networks: [web]
    volumes:
      - ./api/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/app:/var/www/html:ro
    labels:
      - traefik.enable=true
      # Publicar bajo /clinicavm/api (con HTTPS)
      - traefik.http.routers.clinicamv_api.rule=Host(`${DOMAIN}`) && PathPrefix(`/clinicamv/api`)
      - traefik.http.routers.clinicamv_api.entrypoints=websecure
      - traefik.http.routers.clinicamv_api.tls.certresolver=le
      - traefik.http.middlewares.strip-clinicamv.stripprefix.prefixes=/clinicamv
      - traefik.http.routers.clinicamv_api.middlewares=strip-clinicamv
      - traefik.http.routers.clinicamv_api.priority=30