networks:
  web: {}

volumes:
  traefik_letsencrypt: {}
  mysql_data: {}                 # 👈 volumen declarado arriba (no dentro de servicios)

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    networks: [web]
    volumes:
      - traefik_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web-personal:
    image: nginx:alpine
    container_name: web-personal
    restart: unless-stopped
    networks: [web]
    volumes:
      - ./web-personal:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.personal.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)
      - traefik.http.routers.personal.entrypoints=websecure
      - traefik.http.routers.personal.tls.certresolver=le
      - traefik.http.routers.personal.priority=1

  presentacion:
    image: nginx:alpine
    container_name: presentacion
    restart: unless-stopped
    networks: [web]
    volumes:
      - ./presentacion:/usr/share/nginx/html/presentacion:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.presentacion.rule=Host(`${DOMAIN}`) && PathPrefix(`/presentacion`)
      - traefik.http.routers.presentacion.entrypoints=websecure
      - traefik.http.routers.presentacion.tls.certresolver=le
      - traefik.http.routers.presentacion.priority=10

  # FRONTEND Angular servido en /clinicamv
  clinicamv-frontend:
    image: ghcr.io/sebasrodmag/clinicamv-frontend:main
    container_name: clinicamv-frontend
    restart: unless-stopped
    networks: [web]
    labels:
      - traefik.enable=true
      - traefik.http.routers.clinicamv.rule=Host(`${DOMAIN}`) && PathPrefix(`/clinicamv`)
      - traefik.http.routers.clinicamv.entrypoints=websecure
      - traefik.http.routers.clinicamv.tls.certresolver=le
      - traefik.http.routers.clinicamv.priority=20

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks: [web]
    environment:
      MYSQL_DATABASE: clinica_db
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: change-me-root
      TZ: Europe/Madrid
    command: ["--default-authentication-plugin=mysql_native_password","--sql-mode="]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  clinicamv-php:
    image: ghcr.io/sebasrodmag/clinicamv-php:main
    container_name: clinicamv-php
    restart: unless-stopped
    networks: [web]
    depends_on:
      mysql:
        condition: service_healthy         # 👈 espera a MySQL sano
    entrypoint: []                         # 👈 borra entrypoint de la imagen
    command: ["php-fpm","-F"]             # 👈 FPM en foreground
    volumes:
      - ./despliegue-asrm/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./despliegue-asrm/laravel/.env.prod:/var/www/.env:ro
    environment:
      APP_ENV: production

  clinicamv-api:
    image: ghcr.io/sebasrodmag/clinicamv-api:main
    container_name: clinicamv-api
    restart: unless-stopped
    networks: [web]
    depends_on: [clinicamv-php]
    volumes:
      - ./despliegue-asrm/api:/etc/nginx/conf.d:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.clinicamv_api.rule=Host(`${DOMAIN}`) && PathPrefix(`/clinicamv/api`)
      - traefik.http.routers.clinicamv_api.entrypoints=websecure
      - traefik.http.routers.clinicamv_api.tls.certresolver=le
      - traefik.http.middlewares.strip-clinicamv.stripprefix.prefixes=/clinicamv
      - traefik.http.routers.clinicamv_api.middlewares=strip-clinicamv
      - traefik.http.routers.clinicamv_api.priority=30
