name: Build & Push clinicamv-api
on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
      - ".github/workflows/build-api.yml"
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/clinicamv-api:main \
            -f api/Dockerfile \
            api

      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/clinicamv-api:main
