name: Build & Push clinicamv-api

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
      - ".github/workflows/build-api.yml"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login en GHCR con el GITHUB_TOKEN del repo
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build + Push de la imagen de Nginx de la API
      - uses: docker/build-push-action@v5
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: ghcr.io/sebasrodmag/clinicamv-api:main
