name: Build & Push clinicamv-api
on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
      - ".github/workflows/build-api.yml"

  permissions:
      contents: read
      packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: api
          file: api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/clinicamv-api:main

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/clinicamv-api:main \
            -f api/Dockerfile \
            api

      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/clinicamv-api:main
